#:schema node_modules/wrangler/config-schema.json
name = "sublink-work"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "384354787f3f4b14a89b1710b61394cb" }
]
